/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace XpAttestation {
  export type AttestPayloadStruct = {
    user: AddressLike;
    totalXp: BigNumberish;
    nonce: BytesLike;
  };

  export type AttestPayloadStructOutput = [
    user: string,
    totalXp: bigint,
    nonce: string
  ] & { user: string; totalXp: bigint; nonce: string };
}

export interface XpAttestationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestXp"
      | "eip712Domain"
      | "hashPayload"
      | "processedNonces"
      | "signerAuthority"
      | "updateSignerAuthority"
      | "userXp"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EIP712DomainChanged" | "XpAttested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attestXp",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashPayload",
    values: [XpAttestation.AttestPayloadStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "processedNonces",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSignerAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "userXp", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "attestXp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSignerAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userXp", data: BytesLike): Result;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace XpAttestedEvent {
  export type InputTuple = [
    user: AddressLike,
    totalXp: BigNumberish,
    nonce: BytesLike
  ];
  export type OutputTuple = [user: string, totalXp: bigint, nonce: string];
  export interface OutputObject {
    user: string;
    totalXp: bigint;
    nonce: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XpAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): XpAttestation;
  waitForDeployment(): Promise<this>;

  interface: XpAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestXp: TypedContractMethod<
    [
      user: AddressLike,
      totalXp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  hashPayload: TypedContractMethod<
    [payload: XpAttestation.AttestPayloadStruct],
    [string],
    "view"
  >;

  processedNonces: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  signerAuthority: TypedContractMethod<[], [string], "view">;

  updateSignerAuthority: TypedContractMethod<
    [_newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  userXp: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestXp"
  ): TypedContractMethod<
    [
      user: AddressLike,
      totalXp: BigNumberish,
      nonce: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashPayload"
  ): TypedContractMethod<
    [payload: XpAttestation.AttestPayloadStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "processedNonces"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "signerAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateSignerAuthority"
  ): TypedContractMethod<[_newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userXp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "XpAttested"
  ): TypedContractEvent<
    XpAttestedEvent.InputTuple,
    XpAttestedEvent.OutputTuple,
    XpAttestedEvent.OutputObject
  >;

  filters: {
    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "XpAttested(address,uint256,bytes32)": TypedContractEvent<
      XpAttestedEvent.InputTuple,
      XpAttestedEvent.OutputTuple,
      XpAttestedEvent.OutputObject
    >;
    XpAttested: TypedContractEvent<
      XpAttestedEvent.InputTuple,
      XpAttestedEvent.OutputTuple,
      XpAttestedEvent.OutputObject
    >;
  };
}
