name: Sync Backend Database

on:
  push:
    branches: [main]
    paths: ['server/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./server
        run: bun install

      - name: Sincronizar Banco de Dados
        working-directory: ./server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bun run db:push
